/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/DragonBlend.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Dragon(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/DragonBlend.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Dragon">
        <group name="Empty001" position={[0.003, 4.977, 4.052]} />
        <mesh name="Player_BOX" geometry={nodes.Player_BOX.geometry} material={materials['Material.008']} position={[0, 2.496, 0]}>
          <group name="a" rotation={[0.007, 0, 0]} scale={0.172}>
            <primitive object={nodes.pelvic_2} />
            <primitive object={nodes.Bone002} />
            <primitive object={nodes.Helper_Bone} />
            <primitive object={nodes.back_food_L} />
            <primitive object={nodes.Hand_R} />
            <primitive object={nodes.back_food_R} />
            <primitive object={nodes.Hand_L} />
            <primitive object={nodes.Arm_Cont_R001} />
            <primitive object={nodes.Arm_Cont_L001} />
            <primitive object={nodes.back_food_L001} />
            <primitive object={nodes.back_food_R001} />
            <primitive object={nodes.Arm_Cont_L002} />
            <primitive object={nodes.Bone001} />
            <primitive object={nodes.Cont_tail001} />
            <primitive object={nodes.Cont_tail002} />
            <primitive object={nodes.Bone004} />
            <primitive object={nodes.Arm_Cont_R} />
            <primitive object={nodes.Arm_Cont_L} />
            <group name="Cube_1">
              <skinnedMesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Game_dragon.001']} skeleton={nodes.Cube004.skeleton} />
              <skinnedMesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials.Game_dragon} skeleton={nodes.Cube004_1.skeleton} />
              <skinnedMesh name="Cube004_2" geometry={nodes.Cube004_2.geometry} material={materials.EYES} skeleton={nodes.Cube004_2.skeleton} />
            </group>
          </group>
        </mesh>
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.002']} position={[0, 0.519, 0]} rotation={[-Math.PI, 0, 0]} scale={-12450.561} />
        <mesh name="smoke" geometry={nodes.smoke.geometry} material={materials['Material.001']} />
        <mesh name="dragon_fireball_1" geometry={nodes.dragon_fireball_1.geometry} material={materials['Material.009']} />
        <mesh name="smoke2" geometry={nodes.smoke2.geometry} material={materials['Material.001']} />
        <mesh name="dragon_fireball_2" geometry={nodes.dragon_fireball_2.geometry} material={materials['Material.009']} />
        <mesh name="dragon_fireball_3" geometry={nodes.dragon_fireball_3.geometry} material={materials['Material.009']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/DragonBlend.glb')
